# Generated by Django 4.2.16 on 2024-10-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="网页名称"
                    ),
                ),
                (
                    "imgURL",
                    models.ImageField(
                        blank=True, null=True, upload_to="img", verbose_name="图片"
                    ),
                ),
            ],
            options={
                "db_table": "content",
            },
        ),
    ]
